language: cpp
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - nsis
      - cmake
      - xvfb

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo dpkg --add-architecture i386 && sudo rm /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update -q

install:
  - sudo apt-get install wine1.8 -y
  - sudo wget -N https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -P /usr/bin
  # latest swig
  - git clone https://github.com/swig/swig.git
  - pushd swig
  - git checkout rel-3.0.12
  - ./autogen.sh
  - ./configure --without-alllang --prefix=/usr
  - make -j2
  - sudo make install
  - popd

before_script:
  - wget http://downloads.sourceforge.net/openturns/openturns/openturns-1.9/dev/openturns-developers-windeps-1.9.tar.gz -P /tmp

script:
  - git clone https://github.com/openturns/openturns.git
  - pushd openturns
  - git checkout v1.9rc1
  - pushd distro/windows
  - tar xzf /tmp/openturns-developers-windeps-1.9.tar.gz
  - make ot-module-installer PYBASEVER=$PYBASEVER ARCH=$ARCH
  - cp -v *.exe ${TRAVIS_BUILD_DIR}
  - cp -v openturns-mingw-1.9rc1-py${PYBASEVER}-${ARCH}.tar.bz2 ${TRAVIS_BUILD_DIR}
  - popd
  - popd

env:
  matrix:
    - PYBASEVER=2.7 ARCH=i686
    - PYBASEVER=2.7 ARCH=x86_64
    - PYBASEVER=3.5 ARCH=i686
    - PYBASEVER=3.5 ARCH=x86_64
    - PYBASEVER=3.6 ARCH=i686
    - PYBASEVER=3.6 ARCH=x86_64

deploy:
  provider: releases
  api_key:
    secure: JbTI9D1q5LuGrIvKNo6H/F1jPtq9pZNAlqglC0N3gEYQ4L+tmHfGOFxSRdsUaz7j/CgVTjmvKYtrAcYbTKjP7yN6RHS7dX9OvEWFpk3kyTwB9WUQhzew4ccT3sYjdtqlHqdtEcHOGBOA679xm7vIWyP2I7bjCus4gQXJFt53Bn40LZUiTwDg8kYjRleALrOlVetaMGnXRQIh27PlQDqSKUcJ7yyxHY1gkLQ4+gpTA3v2jstaMgI/+TZoqyQjYb66FWmQjOw/FP1ZF0xbTCm9nfXPNbf3Ha81uzQWu5eyJtrs/4kLv6bcNmurBHWxypGPWTJipBFp/129cJ+JgkOXHn/vmQtSupofknVwS5lt2rn36CHPpnD1377uT7WBtFDtuPn1raihqoj2o9jo3uv6aoFHr0qvLQPxnz3rt8SIbxPSGyQmYEc3u4ZTXwyU6i8ZGJJek7mEpuZZsHpQ1/KZjlX6V3ZMwoygE1o/LS4RCnGGZxBnf/6mFSBU8doC3amOHzqskBlotLowXMl++6I1lDCeSCRsUC2QkqsGG5KmYFJlStMzwhp/djdy2GcsIkip0eOh4g2b75iAEaLWBgclxvm013vTmjNdanir1gIBDvO2XmdifcpV24b7eUbg1vBy1vLkH4ZAFotRVehpPu7BnsA8nEDAsyJzf4O8nAbIRic=
  file:
    - ${TRAVIS_BUILD_DIR}/openturns-1.9rc1-py${PYBASEVER}-${ARCH}.exe
    - ${TRAVIS_BUILD_DIR}/openturns-mingw-1.9rc1-py${PYBASEVER}-${ARCH}.tar.bz2
  repo: openturns/build
  skip_cleanup: true
  on:
    tags: true
