name: Release

on: push

jobs:
  mingw:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18rc1]
        pyver: [3.6, 3.7, 3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker pull openturns/archlinux-mingw && docker run -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-mingw /io/run_docker_build.sh ${{ matrix.version }} ${{ matrix.pyver }} `id -u` `id -g`
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            openturns-${{ matrix.version }}-py${{ matrix.pyver }}-x86_64.exe
            openturns-mingw-${{ matrix.version }}-py${{ matrix.pyver }}-x86_64.tar.bz2
